name: DungeonDash
version: 1.1.0
author: hammy3502
main: net.blf02.dungeondash.DungeonDash
api-version: 1.16
commands:
  ddash:
    description: Command for all DungeonDash-related commands.
    usage: /ddash
    permission: dungeondash.any